### ISSUE TITLE
Caracteres especiales con Google

### ISSUE THREAD

**Issue by Idire** [MaDDoGo/metadata.filmaffinity.com#59]
Buenas, quería avisar de que cuando se hace una búsqueda mediante google, al importar los datos se muestran mal los caracteres especiales como tildes y eñes.

**Comment by pancheto** [comment]
hola Idire. lo cierto es que la búsqueda con o sin google sólo afecta a encontrar la película, no al contenido. lo que sí afecta al contenido es lo que la página de FA muestre en cada momento, de ahí que para permitir que una de las dos pudiera fallar el scraper permite consultar tanto la web de escritorio como la web móvil. lo que he visto últimamente (aunque es algo que varía sobre la marcha, por cuestiones internas a FA y por supuesto ajenas al scraper) es que la web móvil está generando un contenido que el scraper procesa mal, pero la web principal sí genera un contenido correcto, así que muy probablemente tu error venga por ahí. si quieres solucionarlo ya comprueba que no estés usando la web móvil, aunque con el tiempo la gente de FA suele acabar arreglando este tipo de problemas.
