### ISSUE TITLE
problema filmaffinity

### ISSUE THREAD

**Issue by enriquecondeconde** [MaDDoGo/metadata.filmaffinity.com#61]
Desde hace unos días metadata.filmaffinity.com 1.6.4 de Kodi 16.1 (Jarvis) no obtiene la información de la película sobre estudios y escritor.

Saludos cordiales

**Comment by asturnauta** [comment]
Yo lo he probado en kodi 15.2 y la información del director sí la obtiene, pero no así la de escritor y estudio.

Un saludo.

**Comment by pancheto** [comment]
efectivamente había un error en el reconocimiento del código de FA en los casos de escritor, estudio y género. he revisado todas las búsquedas a fin de unificarlas y hacerlas algo más sensibles a errores en la nueva versión 1.7.0 del scraper.
