### ISSUE TITLE
Información de género

### ISSUE THREAD

**Issue by enriquecondeconde** [MaDDoGo/metadata.filmaffinity.com#63]
En la información de género, ahora aparece también información de subgéneros.

**Comment by pancheto** [comment]
en un commit reciente se actualizaron muchas búsquedas de información, que afectó también a la información de género: se obtenía toda la información dentro de dicha sección, tanto géneros como topics. en el último commit se han eliminado los topics, pero se han dejado todos los géneros. si con "subgénero" te refieres al resto de los géneros que no sea el primero te indico que lo correcto es dejarlos, pero si te refieres a topics entonces te recomiendo que uses la última versión que tienes aquí mismo (github), donde ya está corregido.

**Comment by MaDDoGo** [comment]
Hola,

si la gente de Kodi no me dice nada, esta tarde miraré otras vías para
notificarles que hay que hacer un pull de código. Creo (y digo creo porque
lo miré por encima) que ahora hay que hacer un Pull Request en los
repositorios de github de kodi-addons

**Comment by enriquecondeconde** [comment]
Lo siento pancheto, me refería a los topics. Gracias una vez más.

**Comment by pancheto** [comment]
no es ningún problema. nos avisaron a través de kodimania.com y se corregió tanto para la versión móvil como para la web completa, pero no está de más que lo pruebe más gente antes de hacerse público para asegurarnos. en caso de detectar algún problema más puedes volver a abrir otro issue, que para eso está.
