### ISSUE TITLE
Valoración IMDB no funciona

### ISSUE THREAD

**Issue by asturnauta** [MaDDoGo/metadata.filmaffinity.com#64]
Hola

He probado a activar la opción de obtener la puntuación a través de IMDB y creo que no funciona.
He probado con la película Star Trek: Más Allá y la puntuación que se guarda en la base de datos es la de filmaffinity.

He activado la depuración y adjunto el log por si sirve para encontrar el error.

http://pastebin.com/x9a5ak1v

Un saludo.

**Comment by pancheto** [comment]
hola. he tratado de reproducir tu problema y me temo que no he sido capaz. por defecto el scraper obtiene la puntuación de FA (un realista 6.1), y en caso de activar la opción de puntuación IMDB la obtiene correctamente (un sorprendente 7.2). en el log se aprecian las llamadas a distintas funciones de IMDB, pero no a la que obtiene la puntuación (GetIMDBRatingById), que se activa cuando la opción de puntuación IMDB está seleccionada. por el log yo diría que la opción no está seleccionada en la configuración general, o es posible que tengas alguna configuración particular para la carpeta de Star Trek que pueda estar pasando por encima la configuración general. desde luego problema del scraper no parece.

**Comment by asturnauta** [comment]
Hola pancheto.
Lo primero gracias por comprobar la opción, y lo segundo perdona que no haya respondido en este tiempo, ho he tenido mucho tiempo libre para hacer pruebas.
Es verdad que he notado algún que otro problema en otros addons, así que aprovechando la nueva versión he pensado hacer una instalación limpia y volver a configurar todo desde cero.
Muchas gracias.
