### ISSUE TITLE
Error al importar "Escritor" 

### ISSUE THREAD

**Issue by asturnauta** [MaDDoGo/metadata.filmaffinity.com#66]
Hola

He descargado el último xml (1.7.2) y ahora importa correctamente el año, pero no se si han cambiado más cosas en filmaffinity ya que me he dado cuenta de que en la información de "Escritor" importa los datos relativos al género y los tags de la web. 

Por ejemplo aparece "Ciencia ficción. Drama |Extraterrestre" 

El resto de campos creo que son correctamente importados. 

Gracias.

**Comment by pancheto** [comment]
gracias por avisar. me temo que es un error que lleva tiempo con nosotros. lo he trazado en mi librería hasta finales de enero 2017, así que cualquier película scrapeada desde entonces debería arrastrar dicho error. lo he solucionado incluso preventivamente en alguna otra categorías dentro de la versión 1.7.3
