### ISSUE TITLE
No carga posters

### ISSUE THREAD

**Issue by poti2** [MaDDoGo/metadata.filmaffinity.com#67]
Buenas tardes, desde hace una semana aproximadamente no carga los posters de las peliculas. Yo tengo Kodi 17.3 (recien actualizado) y la version del scrapper filmaffinity es la 1.7.3
He abierto un mensaje tambien aqui:
https://www.kodimania.com/viewtopic.php?f=13&t=238&start=135
Donde ya somos 4 los usuarios que reportamos el mismo error.

Muchas gracias!

**Comment by pancheto** [comment]
gracias por avisar. problema confirmado: el cambio en la web de FA del protocolo http al https impide, entre otras cosas, la obtención de los posters de FA. ya está corregido en la versión 1.7.4
