### ISSUE TITLE
Problema al scrapear It usando NFO

### ISSUE THREAD

**Issue by asturnauta** [MaDDoGo/metadata.filmaffinity.com#69]
Hola,

Estoy teniendo problemas al añadir la película It, usando un fichero NFO con la siguiente información:

```
<movie>
      <title>Stephen King's It</title>
</movie>
https://www.filmaffinity.com/es/film872097.html
http://www.imdb.com/title/tt0099864/
```

Como al poner solo la url de filmaffinity no cogía bien la información de los posters y fondos de la web themoviedb.com, añadí la segunda url de imdb para ayudarle un poco, cosa que en otras películas sí que me había funcionado bien, pero en esa ocasión no lo hace bien.

Dejo el link del log que he hecho: https://pastebin.com/389AvS3g

Este sistema de la doble url, si bien casi nunca tenía que utilizarlo, para películas que daban problemas me funcionaba bien hasta ahora. Por ejemplo, la película "Bienvendios al fin del mundo" la tenía scrapeada con este nfo: 

> http://www.filmaffinity.com/es/film828213.html
> http://www.imdb.com/title/tt1213663/

No sé muy bien si habrá cambiado algo en la web de filmaffinity o qué podrá ser.

Un saludo.

**Comment by asturnauta** [comment]
Investigando otros errores similares en el scraper de thetvdb.com he conseguido hacerlo funcionar sustituyendo el https:// por el normal http:// en la url del filmaffinity.
Parece que los https no se llevan bien con los scrapers.

Un saludo.

**Comment by jamigo** [comment]
me temo que no veo el problema, al menos en cuanto a lo que al scraper se refiere:
- si el cambio de https por http lo haces en el fichero nfo al scraper le da igual, porque se fija sólo en lo que hay precisamente después del "://"
- si el cambio lo haces en el código del scraper la web de FA lo debería redirigir a https igualmente

en resumen, que no entiendo en qué mejora poner http en lugar de https, salvo que el código de Kodi que lea esas urls sueltas tenga algún problema con https, y en ese caso no sería un problema del scraper. hay una mención al respecto en http://kodi.wiki/view/NFO_files, en el que indican que TVDB no acepta https y que por eso las urls tienen que ir con http. a lo mejor Kodi tiene alguna manera de procesar esa información http/https que pudiera estar metiéndose en medio de todo esto, y eso podría ser la explicación al problema, aunque comentan que en la versión 18 estará "solucionado".

**Comment by pancheto** [comment]
me temo que no veo el problema, al menos en cuanto a lo que al scraper se refiere:
- si el cambio de https por http lo haces en el fichero nfo al scraper le da igual, porque se fija sólo en lo que hay precisamente después del "://"
- si el cambio lo haces en el código del scraper la web de FA lo debería redirigir a https igualmente
en resumen, que no entiendo en qué mejora poner http en lugar de https, salvo que el código de Kodi que lea esas urls sueltas tenga algún problema con https, y en ese caso no sería un problema del scraper. hay una mención al respecto en http://kodi.wiki/view/NFO_files, en el que indican que TVDB no acepta https y que por eso las urls tienen que ir con http. a lo mejor Kodi tiene alguna manera de procesar esa información http/https que pudiera estar metiéndose en medio de todo esto, y eso podría ser la explicación al problema, aunque comentan que en la versión 18 estará "solucionado".
