### ISSUE TITLE
Problemas con scraper filmaffinity

### ISSUE THREAD

**Issue by javier1461** [MaDDoGo/metadata.filmaffinity.com#70]
Buenos días. Filmaffinity no descarga ningún arte (poster, fanart, etc...). Me gustaría que se solucionara el problema porque es el scraper que utilizo desde hace mucho tiempo y quiero seguir utilizándolo.

Gracias de antemano y saludos cordiales

**Comment by pancheto** [comment]
ya está solucionada la conexión con TMDB
