### ISSUE TITLE
Problema al usar .nfo mixto

### ISSUE THREAD

**Issue by asturnauta** [MaDDoGo/metadata.filmaffinity.com#71]
Hola

Estoy teniendo problemas al añadir películas en las que tengo un fichero nfo con información sobre el título y la colección y la url de filmaffinity.
Usaba ese tipo de ficheros cuando quería añadir una película con un título especial, o en otra colección y me venía funcionando bien, aunque no recuerdo cuándo fué la última vez que añadí una película así.

```
El nfo sería algo así:
<movie>
        <title>Star Wars. Episodio VIII: Los últimos Jedi</title>
	<set>Star Wars - La Saga Completa</set>
</movie>
http://www.filmaffinity.com/es/film668878.html
```

Lo que no se muy bien es si es un problema del scraper o de cómo gestiona kodi la información del nfo y la del scraper.

Si puede ser tema del scraper puedo subir el log, y si me decís que sería tema de kodi, cerramos este tema.

Gracias.

**Comment by pancheto** [comment]
confirmado el error del código que impedía procesar correctamente las URLs dentro de los ficheros NFO. en la versión 1.9.4 estará corregido.
