### ISSUE TITLE
Problema de descarga

### ISSUE THREAD

**Issue by javier1461** [MaDDoGo/metadata.filmaffinity.com#72]
Buenos días, el escraper últimamente no descarga las artes (poster, fanart, ...) el resto parece que está bien.

Un saludo

**Comment by pancheto** [comment]
para descargar toda la información adicional a la textual de FA se necesita tener la última versión del scraper de FA (ahora mismo es la 1.9.3) y la última versión del scraper de TMDB (ahora mismo es la 5.1.3 del 10 de mayo). el scraper de FA puede tardar a veces en actualizarse, pero el de TMDB viene con Kodi y su actualización suele ser automática.

**Comment by javier1461** [comment]
Muchísimas gracias, actualizado y funcionando correctamente de nuevo. Un saludo

Enviado desde Yahoo Mail con Android 
 
  El mar., may. 15, 2018 a 17:13, Jorge Amigo<notifications@github.com> escribió:   
para descargar toda la información adicional a la textual de FA se necesita tener la última versión del scraper de FA (ahora mismo es la 1.9.3) y la última versión del scraper de TMDB (ahora mismo es la 5.1.3 del 10 de mayo). el scraper de FA puede tardar a veces en actualizarse, pero el de TMDB viene con Kodi y su actualización suele ser automática.
