### ISSUE TITLE
Posters incorrectos

### ISSUE THREAD

**Issue by cgonzalez76** [MaDDoGo/metadata.filmaffinity.com#75]
Me ha pasado con varias películas para las que existen dos o más títulos similares el mismo año pero la que me acaba de surgir es "X-men 3. La decisión final", descarga el poster de "A todo gas. Tokio race", que no tiene nada que ver salvo el año.
He activado la opción de la búsqueda de google, el descargar posters de fanarts.tv,... pero nada.
¿Será fallo del scraper o de filmaffinity?
Gracias.

**Comment by jamigo** [comment]
sí, me temo que yo también lo he notado. la información de FA se obtiene correctamente, pero la externa (póster incluido) no. hay que revisar la consulta a TMDB.

**Comment by pancheto** [comment]
sí, me temo que yo también lo he notado. la información de FA se obtiene correctamente, pero la externa (póster incluido) no. hay que revisar la consulta a TMDB.

**Comment by pancheto** [comment]
corregido en v1.9.5
