### ISSUE TITLE
Add-on roto en Kodi

### ISSUE THREAD

**Issue by minatalia72** [MaDDoGo/metadata.filmaffinity.com#80]
Hola. 
Llevo usando el add-on de Filmaffinity en Kodi desde que se creó. Para mí no hay otro. El problema es que ya no funciona, me marca como roto. Tengo la versión 1.10 que creo que la descargué de Kodimanía (la web ya no existe).
Alguien tiene alguna versión más reciente que funcione o sabe cómo solucionar el problema?
Muchas gracias.

**Comment by jimbcn** [comment]
A mi me pasa lo mismo tanto leia como matrix
Saludos y gracias

**Comment by pancheto** [comment]
Creo que la versión 1.10 se la inventó el equipo de Kodi para marcarlo como roto ya que hace años que no lo adaptamos a sus nuevas exigencias y no lo mantenemos ya oficialmente. Extraoficialmente, yo lo sigo usando, aunque es cierto que sin poder configurarlo porque no lo adaptamos a su actualización multilenguaje, pero me funcionaba perfectamente hasta hace un par de semanas y no había tenido tiempo de arreglarlo.

El error que ha dado ha sido por un cambio menor en el código de la web de FA. Lo he corregido para mí, así que si alguien más quiere seguir usándolo sólo tiene que sustituir el fichero filmaffinity.xml que tiene Kodi tras instalar el addon por éste, que sería la versión 1.9.8:
https://www.dropbox.com/s/ahu8ooo41uey6ny/filmaffinity.xml?dl=0

**Comment by minatalia72** [comment]
Lo he probado y funciona. Sí que es verdad que las carátulas y el fanart fallan en algunas películas. Pero lo importante es que el resto de información lo añade bien.
No sé como agradecerlo. Muchísimas gracias. Un abrazo.

**Comment by minatalia72** [comment]
Lo he probado y funciona. Sí que es verdad que las carátulas y el fanart
fallan en algunas películas. Pero lo importante es que el resto de
información lo añade bien.
No sé como agradecerlo. Muchísimas gracias. Un abrazo.

**Comment by pancheto** [comment]
El scrapper de FA descarga las carátulas y el fanart a través de TMDB tras hacer una búsqueda algo compleja, basada en el título original y el año para obtener el IMDBid y con él toda la información adicional, que podría estar fallando. Te recomendaría que abrieras otro issue en el que comentaras esos problemas por si pudieran corregirse.
